gitIntegration: test        # <-- replace with your GitRepo integration name
gitRepositoryPath: patbat95008/jfrog-pipelines-integrations-examples  # replace jfrog with your username or org name
artifactoryIntegration: artifactory_int     # <-- replace with your Artifactory integration name
imageName: app_docker_image
artifactoryUrl: pat.7x.gcp   # replace with your server name
sourceRepository: docker-local  # replace local docker repository name created in Artifactory
# prodRepository: su204-docker-prod-local # replace with local docker repository name created in Artifactory
